version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: school_management_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: school_management
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - school_network

  backend:
    build: .
    container_name: school_management_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/school_management?authSource=admin
      JWT_SECRET: your_super_secret_jwt_key_here_change_in_production
      JWT_EXPIRE: 7d
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads
    networks:
      - school_network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: school_management_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - school_network

volumes:
  mongodb_data:

networks:
  school_network:
    driver: bridge